name: Humble CI

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
    branches:
      - '*'

jobs:
  humble_build_and_test:
    uses: naturerobots/github_automation_public/.github/workflows/ros_ci.yaml@main
    secrets: inherit
    with:
      ros_distro: humble
